### ISSUE TITLE
add 1.15.2 support

### ISSUE THREAD

**Issue by Suya1671** [NerdHubMC/DropperDucts#1]
really want to use this in 1.15.2

**Comment by UpcraftLP** [comment]
I'm planning on updating to 1.15.2 / 1.16, but haven't had the time recently. But I didn't forget about it ^^

**Comment by Suya1671** [comment]
> I'm planning on updating to 1.15.2 / 1.16, but haven't had the time recently. But I didn't forget about it ^^

Ok thanks!

**Comment by Suya1671** [comment]
Updated yet?

**Comment by Suya1671** [comment]
Still waiting to add this to my mod pack...
